-- Your SQL goes here
CREATE TABLE access_token (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  client_id INTEGER NOT NULL,
  user_id INTEGER DEFAULT NULL,
  token VARCHAR NOT NULL UNIQUE,
  expires_at INTEGER DEFAULT NULL,
  scope VARCHAR DEFAULT NULL
);

CREATE TABLE auth_code (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  client_id INTEGER NOT NULL,
  user_id INTEGER DEFAULT NULL,
  token VARCHAR NOT NULL UNIQUE,
  redirect_uri TEXT NOT NULL,
  expires_at INTEGER DEFAULT NULL,
  scope VARCHAR DEFAULT NULL
);

CREATE TABLE client (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  random_id VARCHAR NOT NULL,
  redirect_uris TEXT NOT NULL,
  secret VARCHAR NOT NULL,
  allowed_grant_types TEXT NOT NULL
);

CREATE TABLE refresh_token (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  client_id INTEGER NOT NULL,
  user_id INTEGER DEFAULT NULL,
  token VARCHAR NOT NULL UNIQUE,
  expires_at INTEGER DEFAULT NULL,
  scope VARCHAR DEFAULT NULL
);